# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{
  config,
  lib,
  pkgs,
  modulesPath,
  ...
}:

{
  imports = [ (modulesPath + "/installer/scan/not-detected.nix") ];

  boot.initrd.availableKernelModules = [
    "xhci_pci"
    "ahci"
    "nvme"
    "ums_realtek"
    "usb_storage"
    "usbhid"
    "sd_mod"
  ];
  boot.initrd.kernelModules = [ ];
  boot.kernelModules = [
    "kvm-amd"
    "amdgpu"
  ];
  boot.extraModulePackages = [ ];
  fileSystems = {
    "/" = {
      device = "/dev/disk/by-uuid/581436a2-87e9-438a-b277-875b9b9569d8";
      fsType = "ext4";
    };
    "/srv/games" = {
      device = "/dev/disk/by-uuid/d9c81539-ecb8-4a2d-861e-e8deaba1ac17";
      fsType = "ext4";
    };
    "/boot" = {
      device = "/dev/disk/by-uuid/CA63-05C8";
      fsType = "vfat";
      options = [
        "fmask=0022"
        "dmask=0022"
      ];
    };

  };
  boot.initrd.luks.devices."root".device = "/dev/disk/by-uuid/3cadc1f0-172f-42d7-953b-3c044f09edcd";

  swapDevices = [
    { device = "/dev/disk/by-uuid/89bbd5da-c0cc-4914-80fa-7c9098cbf414"; }
  ];
  networking.useDHCP = lib.mkDefault true;
  nixpkgs.hostPlatform = lib.mkDefault "x86_64-linux";
  hardware.cpu.amd.updateMicrocode = true;
  hardware.enableAllFirmware = true;
}
