# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{
  config,
  lib,
  modulesPath,
  ...
}: {
  imports = [
    (modulesPath + "/installer/scan/not-detected.nix")
  ];

  boot.initrd.availableKernelModules = ["xhci_pci" "ahci" "usbhid" "usb_storage" "sd_mod" "sr_mod"];
  boot.initrd.kernelModules = [];
  boot.kernelModules = ["kvm-intel"];
  boot.extraModulePackages = [];

  boot.initrd.luks.devices."root".device = "/dev/disk/by-uuid/726c4510-3738-4463-820a-61352b1a5a0b";
  fileSystems = {
    "/boot" = {
      device = "/dev/disk/by-uuid/B150-0D85";
      fsType = "vfat";
      options = ["fmask=0022" "dmask=0022"];
    };
    "/nix" = {
      device = "/dev/disk/by-uuid/c82c72d1-90f4-4797-ad8d-b87abff30e10";
      fsType = "ext4";
    };
    "/" = {
      device = "/dev/disk/by-uuid/51066081-4dae-43ee-970b-c3ff7d3a8191";
      fsType = "ext4";
    };
  };

  networking.useDHCP = lib.mkDefault true;
  nixpkgs.hostPlatform = lib.mkDefault "x86_64-linux";
  hardware.cpu.intel.updateMicrocode = lib.mkDefault config.hardware.enableRedistributableFirmware;
}
