# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{
  config,
  lib,
  modulesPath,
  ...
}:
{
  imports = [ (modulesPath + "/installer/scan/not-detected.nix") ];

  boot.initrd.availableKernelModules = [
    "xhci_pci"
    "usbhid"
    "usb_storage"
    "sd_mod"
    "sdhci_pci"
  ];
  boot.kernelModules = [ "kvm-intel" ];
  boot.initrd.luks.devices."root".device = "/dev/disk/by-uuid/860f0369-de80-4aea-b9c5-31a127e7df84";

  fileSystems = {
    "/" = {
      device = "/dev/disk/by-uuid/86048cc2-c111-4118-9d9b-03083fccd0d6";
      fsType = "ext4";
    };
    "/boot" = {
      device = "/dev/disk/by-uuid/8E46-6726";
      fsType = "vfat";
      options = [
        "fmask=0022"
        "dmask=0022"
      ];
    };
  };

  swapDevices = lib.singleton {
    device = "/dev/disk/by-uuid/fc1faaf9-2137-4780-a1c0-926cfb3aa99a";
  };

  networking.useDHCP = lib.mkDefault true;
  nixpkgs.hostPlatform = lib.mkDefault "x86_64-linux";
  hardware.cpu.intel.updateMicrocode = lib.mkDefault config.hardware.enableRedistributableFirmware;
  hardware.bluetooth.enable = true;
}
