" Options
set number
set guicursor=""
set nocompatible
set termguicolors
set nowrap
set tabstop=4
set smartindent
set autoindent
set undofile
set hidden
set backspace=indent,eol,start 

filetype plugin on
syntax enable
colorscheme srcery 

" Lua stuff
lua <<EOF
  require 'nvim-tree'.setup({
	 open_on_tab = true,
	 auto_reload_on_write = true,
	 open_on_setup = true,
	 open_on_setup_file = true,
	 update_cwd = true,
	 filters = {
	   dotfiles = true,
	   exclude = { ".git", "."},
	 },
 	 view = {
		 width = 35;
		 preserve_window_proportions = true,
	 },
 	 trash = {
		 require_confirm = false,
	 },
	 renderer = {
	   symlink_destination = false,
	   indent_markers = {
		 enable = true,
	   },
	   icons = {
		show = {
		  file = false,
		  folder = false,
		  folder_arrow = false,
		},
	   },
	 },
	})
EOF

function! ToggleTree()
	lua require "nvim-tree".toggle(false, true)
endfunction


let g:Hexokinase_highlighters = ['backgroundfull']

" Toggle Tree!
inoremap <M-'> <c-o>:call ToggleTree()<CR>
nnoremap <M-'> :call ToggleTree()<CR>

" Tab management
nnoremap <M-t> :tabnew<CR>
nnoremap <M-w> :tabclose<CR>
nnoremap <M-p> :tabnext<CR>
nnoremap <M-o> :tabprev<CR>

" Symbol signature
nnoremap <silent> <M-i> :call CocActionAsync('doHover')<CR>

