" Options
set number
set guicursor=""
set nocompatible
set termguicolors
set nowrap
set tabstop=4
set smartindent
set undofile
set hidden
set backspace=indent,eol,start 

" coc-nvim stuff
set updatetime=300
set cmdheight=2
colorscheme molokai

filetype plugin on
syntax enable

" Lua stuff

lua <<EOF
  require 'nvim-tree'.setup({
	 open_on_tab = true,
	 auto_reload_on_write = true,
	 open_on_setup = true,
	 open_on_setup_file = true,
	 update_cwd = true,
	 filters = {
	   dotfiles = true,
	   exclude = { ".git", "."},
	 },
     view = {
		 adaptive_size = true,
	 },
	 renderer = {
	   indent_markers = {
		 enable = true,
	   },
	   icons = {
		-- show = {
		--   file = false,
		--   folder = false,
		--   folder_arrow = false,
		--   git = false,
		-- },
	   },
	 },
	})
    require 'colorizer'.setup()
EOF


" HJKL Keybindings
inoremap <M-h> <c-o>h
inoremap <M-j> <c-o>j
inoremap <M-k> <c-o>k
inoremap <M-l> <c-o>l

" Tab management
nnoremap <M-t> :tabnew<CR>
nnoremap <M-w> :tabclose<CR>
nnoremap <M-p> :tabnext<CR>
nnoremap <M-o> :tabprev<CR>

" Symbol signature
nnoremap <silent> <M-i> :call CocActionAsync('doHover')<CR>

